# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
##### About
  - name: About
    weight: 1
  - name: Vision
    url: vision
    parent: About
    weight: 1
  - name: Research
    url: research
    parent: About
    weight: 2
  - name: Training
    url: training
    parent: About
    weight: 3
##### Fellowships 
  - name: Fellowships
    weight: 2
  - name: General Information
    url: fellowship
    parent: Fellowships
    weight: 1
  - name: Applications
    url: apply
    parent: Fellowships
    weight: 2
  - name: FAQ
    url: faq
    parent: Fellowships
    weight: 5
##### People
  - name: People
    url: people
    weight: 3
##### Events
  - name: Events
    url: event
    weight: 4
##### News
  - name: News
    url: news
    weight: 5
##### Contact
  - name: Contact
    url: '#contact'
    weight: 6
##### RIT
  - name: RIT
    url: rit
    weight: 7