# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'Mathematics of Quantum Information Science at IPST.'
    twitter: ''
  analytics:
    google_analytics: 'G-3LHTD9B102'
    baidu_tongji: ''
  verification:
    google: '1TsCbReihkWVKbuwvlv5AORFKQsShXzP-7XWcqoZJ4o'
    baidu: ''
# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} <a href="https://anilzen.github.io">Anıl Zenginoğlu</a>. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan. 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    # extra_languages:
    #   - r
    #   - latex
    #   - python
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/anilzen/MathQuantum/'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  # map:
  #   provider: 'mapnik'
  #   api_key: ''
  #   zoom: 15

# Extensions

extensions:
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
